---
title: "Developing Data Products in R - Course Project"
author: "Michal Pluta"
date: "February 10, 2018"
output: ioslides_presentation
---
<style type="text/css">

body, td {
   font-size: 14px;
}
code.r{
  font-size: 10px;
}
pre {
  font-size: 10px
}
</style>

## User Interface 

```{r, eval=FALSE, size="tiny"}
library(shiny)
library(plotly)
# Define UI for application that draws a histogram
shinyUI(fluidPage(
  # Application title
  titlePanel("Bundesliga home goals scored by team"),
  # Sidebar with a multiple select input for team name 
  sidebarLayout(
    sidebarPanel(
      selectInput("Team", label=h4("Select Teams (multiple choice):"),
                  c("Bayern Munchen" = "Bayern Munchen","Hertha BSC" = "Hertha BSC",
                    "1. FC Koln" = "1. FC Koln","FC Schalke 04"= "FC Schalke 04"),
                  multiple = TRUE, selected = c("Bayern Munchen", "FC Schalke 04")),
      sliderInput("dateRange", label = h4("Select Seasons"), min = as.Date("1980", "%Y"), 
                  max =as.Date("2015","%Y") ,value = c(as.Date("2005","%Y"), 
                  as.Date("2010","%Y")), timeFormat = "%Y")),
    # Show a plot
    mainPanel(plotlyOutput("plot"))
  )
))
```

## Server

```{r, eval=FALSE}
library(shiny)
library(engsoccerdata)
library(plotly)
library(dplyr)
# Define server logic required to draw a plot
shinyServer(function(input, output) {
  output$plot <- renderPlotly({
    # generate data from ui.R parameters
    ds_germany = as.data.frame(germany)
    test = ds_germany %>% select(Season,home, hgoal) %>% 
      filter(as.Date(as.character(Season), "%Y") >=  input$dateRange[1] &
               as.Date(as.character(Season), "%Y") <=  input$dateRange[2]  &  
               home %in% input$Team) %>% 
      group_by(home, Season) %>% summarize(SumOfHomeGoals=sum(hgoal))
    p <- plot_ly(test, x = ~Season, y = ~SumOfHomeGoals, color = ~home, 
                 type = 'scatter', mode = 'lines') 
    p
  })
})

```

## Sample plot
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(shiny)
library(engsoccerdata)
library(plotly)
library(dplyr)
   
    # generate data from ui.R parameters
    ds_germany = as.data.frame(germany)
    test = ds_germany %>% 
      select(Season,home, hgoal) %>% 
      filter(Season >=  2005 &
               Season <=  2008  &  
               home %in% c("Borussia Dortmund", "FC Schalke 04")) %>% 
      group_by(home, Season) %>% 
      summarize(SumOfHomeGoals=sum(hgoal))
      
    
    p <- plot_ly(test, x = ~Season, y = ~SumOfHomeGoals, color = ~home, 
                 type = 'scatter', mode = 'lines') 
    p
    
```