---
title: "Developing Data Products in R - Week 3"
author: "Michal Pluta"
date: "February 9, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Markdown and Plot.ly

#### Environment 

```{r env, echo=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(dplyr)
#install.packages("engsoccerdata")
library(engsoccerdata)
set.seed(12342)
ds_germany = as.data.frame(germany)

test = ds_germany %>% 
  select(Season,home, hgoal) %>% 
  filter(Season >= 1980 & 
        home %in% c('Bayern Munchen','Hertha BSC')) %>% 
  group_by(home, Season) %>% 
  summarize(SumOfHomeGoals=sum(hgoal))
```

## Plot_ly

```{r plotly, echo=FALSE, warning=FALSE, message=FALSE}

p <- plot_ly(test, x = ~Season, y = ~SumOfHomeGoals, color = ~home, 
        type = 'scatter', mode = 'lines') %>%
   layout(title = 'Bundesliga: Home Goals Scored since 1980')
p
```

## Plot_ly Code
```{r plotly_code, echo=TRUE, warning=FALSE, message=FALSE}
p <- plot_ly(test, x = ~Season, y = ~SumOfHomeGoals, color = ~home, 
        type = 'scatter', mode = 'lines') %>%
   layout(title = 'Bundesliga: Home Goals Scored since 1980')
```