---
title: "Developing Data Products in R - Week 2"
author: "Michal Pluta"
date: "February 6, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Markdown and Leaflet

#### Environment 

```{r env, echo=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(dplyr)
#install.packages("engsoccerdata")
library(engsoccerdata)
set.seed(12342)
ds_germany = as.data.frame(germany)

test = ds_germany %>% 
  select(Season,home, hgoal) %>% 
  filter(Season == 2015 & 
           home %in% c('Bayern Munchen', 'Hertha BSC' ) ) %>% 
  group_by(home) %>% 
  summarize(SumOfHomeGoals=sum(hgoal)) %>% 
  mutate(name=c('Munich', 'Berlin'), lat = c(48.1351,52.5200 ), 
         lng = c(11.5820, 13.4050), 
         color=c('red', 'blue'))
```

## Bundesliga: Home Goals Scored in 2015

```{r leaflet, echo=FALSE, warning=FALSE, message=FALSE}
m = leaflet(test) %>% addProviderTiles(providers$OpenStreetMap) %>% 
  addMarkers(popup= ~ paste(home, ':', SumOfHomeGoals)) %>% 
  addCircleMarkers(radius = ~SumOfHomeGoals, 
            color = ~ color,  fill = FALSE) 
m
```

## Leaflet Code
```{r leaflet_code, echo=TRUE, warning=FALSE, message=FALSE}
m = leaflet(test) %>% addProviderTiles(providers$OpenStreetMap) %>% 
  addMarkers(popup= ~ paste(home, ':', SumOfHomeGoals)) %>% 
  addCircleMarkers(radius = ~SumOfHomeGoals, 
            color = ~ color,  fill = FALSE) 

```